// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByYAt9hLpuTbWac1VfWi_8Fzbze6rOEpA',
    appId: '1:597972793241:web:7c059e21e3a4d21bb38508',
    messagingSenderId: '597972793241',
    projectId: 'measure-ai-f4b70',
    authDomain: 'measure-ai-f4b70.firebaseapp.com',
    storageBucket: 'measure-ai-f4b70.firebasestorage.app',
    measurementId: 'G-4162G7FDYX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdmbLylEO9W--rbqdLmhN5hNyqc_0Rhmc',
    appId: '1:597972793241:ios:6208966cdd2db40eb38508',
    messagingSenderId: '597972793241',
    projectId: 'measure-ai-f4b70',
    storageBucket: 'measure-ai-f4b70.firebasestorage.app',
    iosBundleId: 'com.example.measureAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByYAt9hLpuTbWac1VfWi_8Fzbze6rOEpA',
    appId: '1:597972793241:web:5f01cef38a9a8534b38508',
    messagingSenderId: '597972793241',
    projectId: 'measure-ai-f4b70',
    authDomain: 'measure-ai-f4b70.firebaseapp.com',
    storageBucket: 'measure-ai-f4b70.firebasestorage.app',
    measurementId: 'G-JBQK1R8XZ7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdmbLylEO9W--rbqdLmhN5hNyqc_0Rhmc',
    appId: '1:597972793241:ios:6208966cdd2db40eb38508',
    messagingSenderId: '597972793241',
    projectId: 'measure-ai-f4b70',
    storageBucket: 'measure-ai-f4b70.firebasestorage.app',
    iosBundleId: 'com.example.measureAi',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtARf_YzBreEo2-a7a1tIPleP3Jh3I6V4',
    appId: '1:597972793241:android:485b9b1aff55d04cb38508',
    messagingSenderId: '597972793241',
    projectId: 'measure-ai-f4b70',
    storageBucket: 'measure-ai-f4b70.firebasestorage.app',
  );

}